export const place = [
  {
    id: 1,
    src: "/image/p-19.jpg",
    sale: "sale",
    heading: "Resort Valley Ocs",
    price: "$7,000 ",
    bedroom: "4BHK",
    bathroom: "4baths",
    sqft: "1200sqft",
    location: " 778 Panama City, FL",
    btn: "View",
  },
  {
    id: 2,
    src: "/image/p-15.jpg",
    sale: "sale",
    heading: "Bluewhale Real Estate",
    price: "$8,000 ",
    bedroom: "3BHK",
    bathroom: "4baths",
    sqft: "1200sqft",
    location: " 778 Panama City, FL",
    btn: "View",
  },
  {
    id: 3,
    src: "/image/p-1.jpg",
    sale: "sale",
    heading: "Bluebell Real Estate",
    price: "$6,000 ",
    bedroom: "4BHK",
    bathroom: "4baths",
    sqft: "1200sqft",
    location: " 778 Panama City, FL",
    btn: "View",
  },
  {
    id: 4,
    src: "/image/p-22.jpg",
    sale: "sale",
    heading: "Agile Real Estate Group",
    price: "$4,400 ",
    bedroom: "4BHK",
    bathroom: "4baths",
    sqft: "1200sqft",
    location: " 778 Panama City, FL",
    btn: "View",
  },
  {
    id: 5,
    src: "/image/p-24.jpg",
    sale: "sale",
    heading: "Bluebell Real Estate",
    price: "$4,400 ",
    bedroom: "4BHK",
    bathroom: "4baths",
    sqft: "1200sqft",
    location: " 778 Panama City, FL",
    btn: "View",
  },
  {
    id: 6,
    src: "/image/p-25.jpg",
    sale: "sale",
    heading: "Bluebell Real Estate",
    price: "$2,400 ",
    bedroom: "4BHK",
    bathroom: "4baths",
    sqft: "1200sqft",
    location: " 778 Panama City, FL",
    btn: "View",
  },
  {
    id: 7,
    src: "/image/p-26.jpg",
    sale: "sale",
    heading: "Agile Real Estate Group",
    price: "$10,400 ",
    bedroom: "4BHK",
    bathroom: "4baths",
    sqft: "1200sqft",
    location: " 778 Panama City, FL",
    btn: "View",
  },
  {
    id: 7,
    src: "/image/p-27.jpg",
    sale: "sale",
    heading: "Agile Real Estate Group",
    price: "$5,400 ",
    bedroom: "4BHK",
    bathroom: "4baths",
    sqft: "1200sqft",
    location: " 778 Panama City, FL",
    btn: "View",
  },
];
